### ISSUE TITLE
WSImport command not working for SharedBooking wsdl v46

### ISSUE THREAD

**Issue by narendraCleartrip** [Travelport/travelport-uapi-tutorial-c-sharp#159]
First of all which tool is recommended for generating java code from travelport WSDL?

I am unable to generate the source code for SharedBooking_v46 wsdl. 
I am getting below error.

com.sun.istack.internal.SAXParseException2; invalid extension element: "soap1:operation" (in namespace "http://schemas.xmlsoap.org/wsdl/soap/")
	at com.sun.tools.internal.ws.wscompile.ErrorReceiver.error(ErrorReceiver.java:78)
	at com.sun.tools.internal.ws.wscompile.ErrorReceiver.error(ErrorReceiver.java:82)
	at com.sun.tools.internal.ws.processor.modeler.wsdl.WSDLModeler.buildModel(WSDLModeler.java:167)
	at com.sun.tools.internal.ws.wscompile.WsimportTool.buildWsdlModel(WsimportTool.java:429)
	at com.sun.tools.internal.ws.wscompile.WsimportTool.run(WsimportTool.java:190)
	at com.sun.tools.internal.ws.wscompile.WsimportTool.run(WsimportTool.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.tools.internal.ws.Invoker.invoke(Invoker.java:159)
	at com.sun.tools.internal.ws.WsImport.main(WsImport.java:42)
Caused by: com.sun.tools.internal.ws.wsdl.framework.ParseException: invalid extension element: "soap1:operation" (in namespace "http://schemas.xmlsoap.org/wsdl/soap/")
	at com.sun.tools.internal.ws.wsdl.parser.Util.fail(Util.java:175)
	at com.sun.tools.internal.ws.wsdl.parser.SOAPExtensionHandler.handleInputOutputExtension(SOAPExtensionHandler.java:237)
	at com.sun.tools.internal.ws.wsdl.parser.SOAPExtensionHandler.handleInputExtension(SOAPExtensionHandler.java:171)
	at com.sun.tools.internal.ws.api.wsdl.TWSDLExtensionHandler.doHandleExtension(TWSDLExtensionHandler.java:71)
	at com.sun.tools.internal.ws.wsdl.parser.AbstractExtensionHandler.doHandleExtension(AbstractExtensionHandler.java:68)
	at com.sun.tools.internal.ws.wsdl.parser.WSDLParser.handleExtension(WSDLParser.java:1049)
	at com.sun.tools.internal.ws.wsdl.parser.WSDLParser.parseBindingOperation(WSDLParser.java:782)
	at com.sun.tools.internal.ws.wsdl.parser.WSDLParser.parseBinding(WSDLParser.java:701)
	at com.sun.tools.internal.ws.wsdl.parser.WSDLParser.parseDefinitionsNoImport(WSDLParser.java:284)
	at com.sun.tools.internal.ws.wsdl.parser.WSDLParser.parseDefinitions(WSDLParser.java:204)
	at com.sun.tools.internal.ws.wsdl.parser.WSDLParser.buildWSDLDocument(WSDLParser.java:193)
	at com.sun.tools.internal.ws.wsdl.parser.WSDLParser.parse(WSDLParser.java:165)
	at com.sun.tools.internal.ws.processor.modeler.wsdl.WSDLModeler.buildModel(WSDLModeler.java:120)
	... 9 more
[ERROR] invalid extension element: "soap1:operation" (in namespace "http://schemas.xmlsoap.org/wsdl/soap/")

**Comment by vivekjyotipramanik** [comment]
Hi narendraCleartrip,

If you are using Java, you can either use CXF or Apache Axis to generate the proxy classes. Thanks.

**Comment by narendraCleartrip** [comment]
@vivekjyotipramanik  I am able to generate the proxy classes using this link , 
[reqAndResponse.zip](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/2722866/reqAndResponse.zip)
https://stackoverflow.com/questions/4455195/how-to-avoid-the-need-to-specify-the-wsdl-location-in-a-cxf-or-jax-ws-generated
But when I am invoking the SOAP service , it is failing and giving namespace issue. Is there anything wrong with WSDL?
