### ISSUE TITLE
I couldn't connect the travelport api from the demo application

### ISSUE THREAD

**Issue by sarvabowmen** [Travelport/travelport-uapi-tutorial-c-sharp#19]
i am receiving the following error 

The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic realm="AXIS"'.

My credentials are 
Universal API User ID:  Universal API/uAPI2660986140-2a7fb891

Universal API Password:  XXXXXXXXXXXXX

Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7009907

URLs:  https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

Please help on this

**Comment by vivekjyotipramanik** [comment]
Hi sarvabowmen,

The URL you are using does not have the servicena,mme at the end of it. If you are using AirService, please use the URL, https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService. For HotelService, Please use the URL, https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/HotelService. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by sarvabowmen** [comment]
Hi Pramanik,

I tried for the AirService through my browser https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService
But it is not logging into the service.

Universal API User ID: Universal API/uAPI2660986140-2a7fb891

Universal API Password: XXXXXXXXXXXXX

Please help me on this..

**Comment by vivekjyotipramanik** [comment]
Hi sarvabowmen,

The URL is not a browser based URL and can't be used using a Browser.
Please use SOAP UI or any SOAP XML Testing tool. Please use the URL endpoint URL in SOAP UI and send the XML request, and you will get back XML response. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by sarvabowmen** [comment]
Hi Vivek,

I also tried from the sample console application it is throwing me the same error. Attached screen shot for your reference..

Attaching the stack trace:
Server stack trace: 
   at System.ServiceModel.Channels.HttpChannelUtilities.ValidateAuthentication(HttpWebRequest request, HttpWebResponse response, WebException responseException, HttpChannelFactory`1 factory)
   at System.ServiceModel.Channels.HttpChannelUtilities.ValidateRequestReplyResponse(HttpWebRequest request, HttpWebResponse response, HttpChannelFactory`1 factory, WebException responseException, ChannelBinding channelBinding)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at ConsoleApplication1.SystemService.SystemPingPortType.service(serviceRequest request)
   at ConsoleApplication1.SystemService.SystemPingPortTypeClient.ConsoleApplication1.SystemService.SystemPingPortType.service(serviceRequest request) in f:\My Projects\travelport-uapi-tutorial-c-sharp-master\travelport-uapi-tutorial-c-sharp-master\ConsoleApplication1\ConsoleApplication1\Service References\SystemService\Reference.cs:line 9700
   at ConsoleApplication1.SystemService.SystemPingPortTypeClient.service(PingReq PingReq) in f:\My Projects\travelport-uapi-tutorial-c-sharp-master\travelport-uapi-tutorial-c-sharp-master\ConsoleApplication1\ConsoleApplication1\Service References\SystemService\Reference.cs:line 9706
   at UAPIConsumptionSamples.TutorialOne.Main(String[] args) in f:\My Projects\travelport-uapi-tutorial-c-sharp-master\travelport-uapi-tutorial-c-sharp-master\ConsoleApplication1\ConsoleApplication1\TutorialOne.cs:line 76

**Note:
I think i am getting the same error as reported in this issue https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/issues/1
**



![error](https://cloud.githubusercontent.com/assets/17758649/15136118/c603dd5a-169b-11e6-9401-e37b2eac7824.PNG)
![service](https://cloud.githubusercontent.com/assets/17758649/15136127/d8d6c3b6-169b-11e6-841d-87d87d9cf150.PNG)

**Comment by vivekjyotipramanik** [comment]
Hi sarvabowmen,

Looks like your account is locked. Could you please provide the TargetBranch and Useranme you are using. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by sarvabowmen** [comment]
Credentials: Universal API Web Services

Universal API User ID:  Universal API/uAPI2660986140-2a7fb891

Universal API Password:  mX2T8nHd7sgTs3rYhx5pcTt7Z

Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7009907

URLs:  https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

**Comment by vivekjyotipramanik** [comment]
Hi sarvabowmen,

We are working on to unlock the account. As soon as it is unlocked I will provide an update. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by sarvabowmen** [comment]
Hi Vivek,

Please let me know once you have unlocked my account.. Thanks in advance

**Comment by sarvabowmen** [comment]
Hi Vivek,

Any Update regarding this..

**Comment by vivekjyotipramanik** [comment]
Hi sarvabowmen,

Our team is working on to unlock this account. We are expecting it to be unlocked by Monday.
I will provide an update as soon as it is unlocked. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by vivekjyotipramanik** [comment]
Hi sarvabowmen,

Could you please try again. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by sarvabowmen** [comment]
Will try and update you thanks Vivek

On Thu, Jun 2, 2016 at 4:25 AM, vivekjyotipramanik <notifications@github.com

**Comment by sarvabowmen** [comment]
Thank Vivek, It is working fine now
